language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false

jdk:
  - oraclejdk8
  - openjdk7

notifications:
  email: false

# Skip the Travis CI's default install command
install: true

script:
- ./mvnw clean verify

# Fix 'Expected feature release number in range of 9 to 14' error on xenial and bionic
dist: trusty
