language: java

matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8
    - os: linux
      sudo: false
      jdk: openjdk7
    - os: linux
      sudo: required
      group: edge
      jdk: ibmjava8

notifications:
  email: false

# Skip the Travis CI's default install command
install: true

script:
- ./mvnw clean verify
