= Introduction

`editorconfig-maven-plugin` is a Maven plugin for checking whether project files comply with format rules
defined in `http://editorconfig.org/[.editorconfig]` files and eventually also for fixing the violations.

WARNING: `editorconfig-maven-plugin` is new. Expect issues of all kinds which is not to say that you should not
https://github.com/ec4j/editorconfig-maven-plugin/issues[report] them :)

== Basic usage

`editorconfig-maven-plugin` requires Java {maven-compiler-target}+ and Maven {project-prerequisites-maven}+.

To make the build fail if any of your source files does not comply with `.editorconfig` rules, add the following to your project:

[source,xml,subs=attributes+]
----
  <plugin>
    <groupId>org.ec4j.maven</groupId>
    <artifactId>editorconfig-maven-plugin</artifactId>
    <version>{project-version}</version>
    <executions>
      <execution>
        <id>check</id>
        <phase>verify</phase>
        <goals>
          <goal>check</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <excludes>
        <!-- Note that maven submodule directories and many non-source file patterns are excluded by default -->
        <!-- - see https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Constants.java#L37
        <!-- You can exclude further files from processing: -->
        <exclude>src/main/**/*.whatever</exclude>
      </excludes>
      <!-- All files are included by default:
      <includes>
        <include>**</include>
      </includes>
      -->
    </configuration>
  </plugin>
----

In case any violations are detected, you may want to fix them automagically by running

[source,xml]
----
mvn editorconfig:format
----


== How it works

`editorconfig-maven-plugin` is designed around the Linter interface.
https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Linter.java[Linter]
is a processor specialized for some particular file format (such as YAML or XML) for which it can detect whether some
particular `.editorconfig` properties are satisfied and eventually propose a
https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Edit.java[fix] that can
be applied automatically.

.Linters available in `editorconfig-maven-plugin`
[cols="1,1,1,4"]
|===
|Class name |Default includes|Default excludes |Supported `.editorconfig` properties

|https://github.com/ec4j/editorconfig-maven-plugin/blob/master/src/main/java/org/ec4j/maven/linters/TextLinter.java[TextLinter]
|`pass:[**/*]`
|
|`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line[end_of_line]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#trim_trailing_whitespace[trim_trailing_whitespace]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#insert_final_newline[insert_final_newline]`

|https://github.com/ec4j/editorconfig-maven-plugin/blob/master/src/main/java/org/ec4j/maven/linters/XmlLinter.java[XmlLinter]
|`pass:[**/*.xml]`, `pass:[**/*.xsl]`
|
|`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style[indent_style]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size[indent_size]`
|===


Contributions of further Linters are highly welcome! Please
https://github.com/ec4j/editorconfig-maven-plugin/issues[open an issue] when you start working on something to avoid
duplicate work.
